/**
 * Fetches event venues (restaurants, wedding halls, salons) for each city
 * using Google Places Text Search API, and outputs venueData.ts.
 *
 * Usage: npx tsx scripts/fetchVenues.ts
 *
 * Requires GOOGLE_PLACES_KEY env var (server key with Places API enabled).
 * The browser key from .env works only if not HTTP-referrer restricted.
 */

const API_KEY = process.env.GOOGLE_PLACES_KEY ?? "AIzaSyBAd_AGvtxO0ULtSbPeTMcyZ2csARrSgXU";
const DELAY_MS = 300;

const CITIES: { slug: string; name: string }[] = [
  { slug: "sibiu", name: "Sibiu" },
  { slug: "cluj", name: "Cluj-Napoca" },
  { slug: "dej", name: "Dej" },
  { slug: "gherla", name: "Gherla" },
  { slug: "huedin", name: "Huedin" },
  { slug: "alba-iulia", name: "Alba Iulia" },
  { slug: "sebes", name: "Sebeș" },
  { slug: "aiud", name: "Aiud" },
  { slug: "blaj", name: "Blaj" },
  { slug: "cugir", name: "Cugir" },
  { slug: "turda", name: "Turda" },
  { slug: "arad", name: "Arad" },
  { slug: "brasov", name: "Brașov" },
  { slug: "targu-mures", name: "Târgu Mureș" },
  { slug: "reghin", name: "Reghin" },
  { slug: "sighisoara", name: "Sighișoara" },
  { slug: "sovata", name: "Sovata" },
  { slug: "ludus", name: "Luduș" },
  { slug: "campia-turzii", name: "Câmpia Turzii" },
  { slug: "oradea", name: "Oradea" },
  { slug: "bistrita", name: "Bistrița" },
  { slug: "beclean", name: "Beclean" },
  { slug: "nasaud", name: "Năsăud" },
  { slug: "sangeorz-bai", name: "Sângeorz-Băi" },
  { slug: "medias", name: "Mediaș" },
  { slug: "timisoara", name: "Timișoara" },
  { slug: "targu-lapus", name: "Târgu Lăpuș" },
  { slug: "cisnadie", name: "Cisnădie" },
  { slug: "avrig", name: "Avrig" },
];

const SEARCH_QUERIES = [
  "sală de nunți",
  "restaurant evenimente",
  "salon petreceri",
  "locație nuntă",
  "restaurant nuntă",
];

interface PlacesResult {
  place_id: string;
  name: string;
  formatted_address: string;
  rating?: number;
  user_ratings_total?: number;
  types: string[];
}

interface PlacesResponse {
  results: PlacesResult[];
  status: string;
  next_page_token?: string;
}

function toSlug(text: string): string {
  return text
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function delay(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function searchPlaces(query: string, cityName: string): Promise<PlacesResult[]> {
  const fullQuery = encodeURIComponent(`${query} ${cityName}`);
  const url = `https://maps.googleapis.com/maps/api/place/textsearch/json?query=${fullQuery}&language=ro&region=ro&key=${API_KEY}`;

  const response = await fetch(url);
  const data = (await response.json()) as PlacesResponse;

  if (data.status !== "OK" && data.status !== "ZERO_RESULTS") {
    console.warn(`  ⚠ Places API status: ${data.status} for "${query} ${cityName}"`);
  }

  return data.results ?? [];
}

async function fetchVenuesForCity(citySlug: string, cityName: string): Promise<VenueOutput[]> {
  const seen = new Set<string>();
  const venues: VenueOutput[] = [];

  for (const query of SEARCH_QUERIES) {
    await delay(DELAY_MS);
    const results = await searchPlaces(query, cityName);

    for (const place of results) {
      if (seen.has(place.place_id)) continue;
      seen.add(place.place_id);

      venues.push({
        placeId: place.place_id,
        slug: toSlug(place.name),
        name: place.name,
        citySlug,
        address: place.formatted_address,
        rating: place.rating,
        reviewCount: place.user_ratings_total,
        types: place.types,
      });
    }
  }

  return venues;
}

interface VenueOutput {
  placeId: string;
  slug: string;
  name: string;
  citySlug: string;
  address: string;
  rating?: number;
  reviewCount?: number;
  types: string[];
}

function renderVenueDataTs(venues: VenueOutput[]): string {
  const lines = venues.map((venue) => {
    return `  {
    placeId: ${JSON.stringify(venue.placeId)},
    slug: ${JSON.stringify(venue.slug)},
    name: ${JSON.stringify(venue.name)},
    citySlug: ${JSON.stringify(venue.citySlug)},
    address: ${JSON.stringify(venue.address)},
    ${venue.rating !== undefined ? `rating: ${venue.rating},` : ""}
    ${venue.reviewCount !== undefined ? `reviewCount: ${venue.reviewCount},` : ""}
    types: ${JSON.stringify(venue.types)},
  }`;
  });

  return `// Auto-generated by scripts/fetchVenues.ts — do not edit manually
// Re-run the script to refresh venue data

export interface VenueData {
  placeId: string;
  slug: string;
  name: string;
  citySlug: string;
  address: string;
  rating?: number;
  reviewCount?: number;
  types: string[];
}

export const VENUES: VenueData[] = [
${lines.join(",\n")}
];

export function getVenuesByCitySlug(citySlug: string): VenueData[] {
  return VENUES.filter((venue) => venue.citySlug === citySlug);
}

export function getVenueBySlug(slug: string, citySlug: string): VenueData | undefined {
  return VENUES.find((venue) => venue.slug === slug && venue.citySlug === citySlug);
}
`;
}

async function main() {
  console.log(`Fetching venues for ${CITIES.length} cities...`);
  console.log(`Queries per city: ${SEARCH_QUERIES.length}`);
  console.log(`Estimated API calls: ~${CITIES.length * SEARCH_QUERIES.length}\n`);

  const allVenues: VenueOutput[] = [];

  for (const city of CITIES) {
    process.stdout.write(`📍 ${city.name}... `);
    try {
      const venues = await fetchVenuesForCity(city.slug, city.name);
      allVenues.push(...venues);
      console.log(`${venues.length} venues`);
    } catch (error) {
      console.log(`ERROR: ${error}`);
    }
  }

  console.log(`\nTotal venues found: ${allVenues.length}`);

  const outputPath = new URL("../src/client/pages/LocationSEO/venueData.ts", import.meta.url).pathname;
  await Bun?.write(outputPath, renderVenueDataTs(allVenues)).catch(async () => {
    const { writeFile } = await import("fs/promises");
    await writeFile(outputPath, renderVenueDataTs(allVenues), "utf-8");
  });

  console.log(`\n✅ Written to src/client/pages/LocationSEO/venueData.ts`);
  console.log(`\nNext steps:`);
  console.log(`  1. Check venueData.ts for quality`);
  console.log(`  2. Add VENUE_ROUTES to locationData.ts`);
  console.log(`  3. Create VenuePage component`);
  console.log(`  4. Add routes to publicRoutes.tsx`);
}

main().catch(console.error);
